[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "turtles"
version = "1.1.0"
requires-python = ">= 3.10"
dependencies = [
    "numpy>=2.0.2",
    "pandas>=2.2.3",
    "scipy>=1.13.1",
    "matplotlib>=3.9.4",
]
description = "GLMs in Python."
readme = "README.md"
license = {file = "LICENSE.txt"}
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
authors = [
    {name = "Adam Motzel", email = "motzel.adam@gmail.com"}
]

[project.optional-dependencies]
dev = [
    "pytest>=8.3.4",
    "pytest-cov>=6.2.1",
    "scikit-learn>=1.6.1",
    "statsmodels>=0.14.4",
    "ipykernel>=6.29.5"
]

[tool.setuptools.packages.find]
where = ["."]
exclude = ["tests", "*tests*", "examples", "scripts"]
